# Generated by Django 3.0.8 on 2020-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0004_auto_20200729_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='bmi_output',
            field=models.IntegerField(default=0),
        ),
    ]
