# Generated by Django 3.0.8 on 2020-07-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0007_auto_20200730_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='bmi_output',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
