# Generated by Django 3.0.8 on 2020-07-28 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi_input', models.ImageField(height_field='picture_height', max_length=255, upload_to='bmi/%Y/%m/%d', width_field='picture_width')),
                ('bmi_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
