# Generated by Django 3.0.8 on 2020-07-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='bmi_output',
            field=models.ImageField(default='static/img/default.jpg', max_length=255, upload_to='bmi/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='bmi_input',
            field=models.ImageField(max_length=255, upload_to='bmi/%Y/%m/%d'),
        ),
    ]
