# Generated by Django 3.0.8 on 2020-07-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0003_remove_bmi_bmi_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='name',
            field=models.CharField(default='officer', max_length=20),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='bmi_input',
            field=models.ImageField(max_length=255, upload_to='bmi/input/%Y/%m/%d'),
        ),
    ]
