# Generated by Django 3.0.8 on 2020-08-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0008_auto_20200730_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='bmi_input',
            field=models.ImageField(max_length=255, upload_to='bmi/input'),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='bmi_output',
            field=models.CharField(max_length=20),
        ),
    ]
