# Generated by Django 3.0.8 on 2020-08-02 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_input', models.ImageField(max_length=255, upload_to='voice/input')),
                ('voice_date', models.DateTimeField(default=datetime.datetime.now)),
                ('voice_output', models.CharField(max_length=20)),
            ],
        ),
    ]
