# Generated by Django 3.0.8 on 2020-08-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='voice_input',
            field=models.ImageField(max_length=255, upload_to='voice/input/'),
        ),
    ]
