# Generated by Django 3.0.8 on 2020-07-28 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_input', models.ImageField(max_length=255, upload_to='uniform/%Y/%m/%d')),
                ('uni_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
