# Generated by Django 3.0.8 on 2020-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='uni_input',
            field=models.ImageField(max_length=255, upload_to='uniform/input/%Y/%m/%d'),
        ),
    ]
