# Generated by Django 3.0.8 on 2020-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0003_auto_20200730_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform_model',
            name='uni_output',
            field=models.CharField(default='All Okay', max_length=50),
        ),
    ]
