# Generated by Django 3.0.8 on 2020-08-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0005_auto_20200730_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform_model',
            name='uni_input',
            field=models.ImageField(max_length=255, upload_to='uniform/input'),
        ),
    ]
