# Generated by Django 3.0.8 on 2020-08-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0006_auto_20200802_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform_model',
            name='uni_input',
            field=models.ImageField(max_length=255, upload_to='uniform/input/'),
        ),
    ]
